name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: 'Name of the artifact to deploy'
                required: false
                type: string
                default: 'dist'
        secrets:
            some-secret:
                description: 'A secret required for deployment'
                required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output test secret
        run: echo "The secret is ${{ secrets.some-secret }}"
      - name: List files
        run: ls -alR
      - name: Output information
        run: echo "This is a reusable workflow for deployment."